services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: agnohq/pgvector:16
    environment:
      POSTGRES_DB: agno
      POSTGRES_USER: agno
      POSTGRES_PASSWORD: agno
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agno"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
